version: '3.1'
services:
  db:
    container_name: PGCustomerDB
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=customerdb
    volumes:
      - ./postgresms:/opt/dctm/odbc
    ports:
      - "5433:5432"