version: '3.1'
services:
  db:
    container_name: MySQLMailSenderDB
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mailsenderdb
    volumes:
      - ./mysqlms:/opt/dctm/odbc
    ports:
      - "3308:3306"